/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRandomMask, IRandomMaskInterface } from "../IRandomMask";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "randomNum",
        type: "uint256",
      },
    ],
    name: "mintRandomMask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRandomMask__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomMaskInterface {
    return new utils.Interface(_abi) as IRandomMaskInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomMask {
    return new Contract(address, _abi, signerOrProvider) as IRandomMask;
  }
}
