/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface PrivateVaultInterface extends utils.Interface {
  functions: {
    "getLabelByIndex(uint64)": FunctionFragment;
    "getLabelByName(string)": FunctionFragment;
    "labelName(uint64)": FunctionFragment;
    "minted()": FunctionFragment;
    "saveWithMinting(string,string)": FunctionFragment;
    "saveWithoutMinting(string,string)": FunctionFragment;
    "total()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getLabelByIndex"
      | "getLabelByName"
      | "labelName"
      | "minted"
      | "saveWithMinting"
      | "saveWithoutMinting"
      | "total"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLabelByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLabelByName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "labelName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "minted", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "saveWithMinting",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "saveWithoutMinting",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "total", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getLabelByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLabelByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "labelName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saveWithMinting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saveWithoutMinting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "total", data: BytesLike): Result;

  events: {};
}

export interface PrivateVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PrivateVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLabelByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getLabelByName(name: string, overrides?: CallOverrides): Promise<[string]>;

    labelName(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    minted(overrides?: CallOverrides): Promise<[boolean]>;

    saveWithMinting(
      data: string,
      cryptoLabel: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    saveWithoutMinting(
      data: string,
      cryptoLabel: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    total(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getLabelByIndex(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getLabelByName(name: string, overrides?: CallOverrides): Promise<string>;

  labelName(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  minted(overrides?: CallOverrides): Promise<boolean>;

  saveWithMinting(
    data: string,
    cryptoLabel: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  saveWithoutMinting(
    data: string,
    cryptoLabel: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  total(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getLabelByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getLabelByName(name: string, overrides?: CallOverrides): Promise<string>;

    labelName(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    minted(overrides?: CallOverrides): Promise<boolean>;

    saveWithMinting(
      data: string,
      cryptoLabel: string,
      overrides?: CallOverrides
    ): Promise<void>;

    saveWithoutMinting(
      data: string,
      cryptoLabel: string,
      overrides?: CallOverrides
    ): Promise<void>;

    total(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getLabelByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLabelByName(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    labelName(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minted(overrides?: CallOverrides): Promise<BigNumber>;

    saveWithMinting(
      data: string,
      cryptoLabel: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    saveWithoutMinting(
      data: string,
      cryptoLabel: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    total(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getLabelByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLabelByName(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    labelName(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    saveWithMinting(
      data: string,
      cryptoLabel: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    saveWithoutMinting(
      data: string,
      cryptoLabel: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    total(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
