/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RegistryInterface extends utils.Interface {
  contractName: "Registry";
  functions: {
    "getEncryptMachine(string)": FunctionFragment;
    "machineHasRegister(address)": FunctionFragment;
    "registryEncryptMachine(string,address)": FunctionFragment;
    "setMachineOwner(string,address)": FunctionFragment;
    "updateEncryptMachine(string,address)": FunctionFragment;
    "versionHasRegister(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getEncryptMachine",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "machineHasRegister",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registryEncryptMachine",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMachineOwner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEncryptMachine",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "versionHasRegister",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "machineHasRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registryEncryptMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMachineOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEncryptMachine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "versionHasRegister",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Registry extends BaseContract {
  contractName: "Registry";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getEncryptMachine(
      version: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    machineHasRegister(
      machine: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    registryEncryptMachine(
      version: string,
      machine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMachineOwner(
      version: string,
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateEncryptMachine(
      version: string,
      machine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    versionHasRegister(
      version: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getEncryptMachine(
    version: string,
    overrides?: CallOverrides
  ): Promise<string>;

  machineHasRegister(
    machine: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  registryEncryptMachine(
    version: string,
    machine: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMachineOwner(
    version: string,
    owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateEncryptMachine(
    version: string,
    machine: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  versionHasRegister(
    version: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getEncryptMachine(
      version: string,
      overrides?: CallOverrides
    ): Promise<string>;

    machineHasRegister(
      machine: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registryEncryptMachine(
      version: string,
      machine: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setMachineOwner(
      version: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateEncryptMachine(
      version: string,
      machine: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    versionHasRegister(
      version: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getEncryptMachine(
      version: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    machineHasRegister(
      machine: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registryEncryptMachine(
      version: string,
      machine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMachineOwner(
      version: string,
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateEncryptMachine(
      version: string,
      machine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    versionHasRegister(
      version: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getEncryptMachine(
      version: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    machineHasRegister(
      machine: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registryEncryptMachine(
      version: string,
      machine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMachineOwner(
      version: string,
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateEncryptMachine(
      version: string,
      machine: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    versionHasRegister(
      version: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
