/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as constantSol from "./Constant.sol";
export type { constantSol };
import type * as permissionSol from "./Permission.sol";
export type { permissionSol };
